### ISSUE TITLE
Possibly increased key chatter since updating to Animus Innova?

### ISSUE THREAD

**Issue by quarterto** [blahlicus/animus-family#12]
Not sure if this is hardware or software. My Terminus Mini was out of use for a few months before I updated the firmware.

**Comment by blahlicus** [comment]
Hey, would you mind describing the problem more in depth? how frequent was the issue and when you say "key chatter," what exactly do you mean?

**Comment by quarterto** [comment]
I mean occasional phantom double keypresses on certain keys. Now I describe it it sounds more likely hardware.

**Comment by blahlicus** [comment]
I see, could you be slightly more descriptive on the double keypresses? How frequent does it happen? Does the speed of which you type at affect the double keypresses? I could configure a build with a slower refresh delay for you and see if it helps with the situation or not.

**Comment by seemuth** [comment]
Or we could implement debouncing in addition to the current edge detection.

For example: require a key to be read in the same state (LOW or HIGH) for two consecutive scans before considering that the new state.

**Comment by blahlicus** [comment]
@seemuth yeah that is a good idea, I'll be overhauling the matrix scanning part with debouncing settings and per-switch timeouts so that they keyboard would have more accurate debouncing and faster response time as part of the port to STM32.

Currently, the entire matrix is scanned asynchronously from the microcontroller clock once every `refreshDelay` ms, I plan to make it such that each switch has a timeout on its own before it is activated again in addition to having consecutive HIGH state checks, that should make the matrix more responsive and more accurate, see pseudocode below:

```

byte[row][col] timeout;
int refreshDelay = 10;

if (1ms passed)
{
    for(int i = 0; i < row; i++)
    {
        for (int j = 0; j < col; j++)
        {
            if (timeout[i][j] == 0)
            {
                timeout[i][j] == refreshDelay;

                // check if pin is HIGH and was LOW previously, and check debouncing, then perform keypress, etc

            }
            else
            {
                timeout[i][j]--;
            }
        }
    }
}
```

Do you think that's a good idea?

**Comment by seemuth** [comment]
@blahlicus What do we gain by adding per-switch timeouts? Cherry MX switches (for example) are specified as having a ≤ 5ms bounce time, so I think we're OK scanning the whole matrix every 3–5 ms.

Regarding debouncing, I suggest something like:

```byte[row][col] keyRawCur; // Current raw (possibly bouncing) key states
byte[row][col] keyRawPrev; // Previous raw (possibly bouncing) key states
byte[row][col] keyStableCur; // Current stable (debounced) key states
byte[row][col] keyStablePrev; // Previous stable (debounced) key states

if (TIMEOUT passed) // where TIMEOUT is 3--5 ms
{
    for (int i = 0; i < row; i++)
    {
        for (int j = 0; j < col; j++)
        {
            keyRawCur[i][j] = READ_THE_KEY();
            if (keyRawCur[i][j] == keyRawPrev[i][j])
            {
                keyStableCur[i][j] = keyRawCur[i][j];

                if (keyStableCur[i][j] != keyStablePrev[i][j])
                {
                        // Handle key press or key release event
                }
            }
            keyRawPrev[i][j] = keyRawCur[i][j];
            keyStablePrev[i][j] = keyStableCur[i][j];
        }
    }
}
```

We don't actually need to use 4 arrays—`keyRawCur` and `keyStableCur` can be scalars used only within the loop. I left the code as-is for clarity. We can optimize it once it's debugged. 😄

**Comment by blahlicus** [comment]
Yeah, I suppose you are right, no point over-complicating the core matrix scanner with too much async stuff, that'll just make it a lot harder to debug when things go wrong.

I'll have that implemented before the STM32 port and have it use a single byte[row][col] array as per your scalar suggestion.

**Comment by seemuth** [comment]
Yep, that sounds good!

As a heads-up, you'll need the two byte[row][col] arrays: both `keyRawPrev` and `keyStablePrev` need to be retained between successive key scans.

**Comment by joefiorini** [comment]
I have this issue as well. Certain keys tend to repeat on a single press ("space" seems to be the most frequent offender, but others do it as well).

I have this issue as well. Certainkeys tend to either repeat on single press and some presses end up not registering until I hit the key a couple times ("space" seems to be the most frequent offender but other keys do it as well). I'm running on the latest Animus master, and using Cherry white switches. I realize that my switches are stiff enough to trigger multiple presses without fully releasing the key, and shaky hands _could_ cause unintended repeats, but sometimes I'll get as many as 5-7 of a single character from a single press. It seems to happen most offten when I'm typing many, many sentences very quckly. That is also when it's the most aggravating.

From what I could from some basic debugging, it seems like the hardware is triggering multiple presses, therefore it seems like the debounce would fix this. My Arduino skills aren't quite there to be able to quickly implement this (I tried to implement @seemuth's psuedo-code last night, but could not get it workiing); I may gve it a try if I'm feeling ambitious. Either way,  not sure if others are experiencing thiis issue, but it would vastly improve my experience with Animus-based keyboards.

(Note: I did not edt mis-fired key presses in this post to better illustrate the issue)

**Comment by seemuth** [comment]
Sorry for any confusion in my pseudocode, @joefiorini. I've drawn up a digital circuit diagram in the hope that it clears up how the debouncing and edge detection is intended to work. The flip-flops are "clocked" at the same time, once per sample of the key input.

![keyboarddebouncing](https://user-images.githubusercontent.com/3700105/30613020-2bba5da8-9d4c-11e7-96a1-3038943b380d.jpg)

For extra efficiency points, you can translate this method into a set of bitwise operations on bytes or words, instead of computing the debouncing and edge detection one key at a time. This is left as an exercise for the reader. :smile:

**Comment by joefiorini** [comment]
Wow, thanks fofr the details @seemuth. I threw together a basic implementation based on the [Arduino debounce tutorial](https://www.arduino.cc/en/Tutorial/Debounce). I'm not sure iffffff it's as advanced as yours, but iit has seemed like it was  helping (until I started writing this reply, now as is evidenced by the typos, I'm not so sure). Here's the diff for my implementation:


```diff
diff --git a/keyboard-specific-builds/diverge-2/diverge-2-master/animus/animus_main.ino b/keyboard-specific-builds/diverge-2/diverge-2-master/animus/animus_main.ino
index 86dfb5a..8efe8eb 100644
--- a/keyboard-specific-builds/diverge-2/diverge-2-master/animus/animus_main.ino
+++ b/keyboard-specific-builds/diverge-2/diverge-2-master/animus/animus_main.ino
@@ -14,6 +14,7 @@ int TempLayer = 0;
 
 // key states
 int KeyState[COL][ROW];
+int KeyStateDebounced[COL][ROW];
 int PreviousState[COL][ROW];
 int LayerState[COL][ROW];
 
@@ -23,6 +24,9 @@ boolean IS_MASTER = true;
 // spacefn keys
 boolean PressedKey = false;
 
+int lastDebounceTime = 0;
+int debounceDelay = 5;
+
 // baud: dont change this it messes with the GUI interface
 int BaudRate = 19200;
 
@@ -58,20 +62,28 @@ void loop()
 
     // main loop starts
     KeyScan();
+
     for (int i = 0; i < ROW; i++)
     {
       for (int j = 0; j < COL; j++)
       {
-        if (PreviousState[j][i] != KeyState[j][i])
-        {
-          if (KeyState[j][i] == HIGH)
-          {
-            LayerState[j][i] = TempLayer;
-            PressKey(GetValEEPROM(j, i, TempLayer), GetTypeEEPROM(j, i, TempLayer));
-          }
-          else
+        if (KeyState[j][i] != PreviousState[j][i]) {
+          lastDebounceTime = millis();
+        }
+
+        if ((millis() - lastDebounceTime) > debounceDelay) {
+          if (KeyState[j][i] != KeyStateDebounced[j][i])
           {
-            ReleaseKey(GetValEEPROM(j, i, LayerState[j][i]), GetTypeEEPROM(j, i, LayerState[j][i]));
+            KeyStateDebounced[j][i] = KeyState[j][i];
+            if (KeyState[j][i] == HIGH)
+            {
+              LayerState[j][i] = TempLayer;
+              PressKey(GetValEEPROM(j, i, TempLayer), GetTypeEEPROM(j, i, TempLayer));
+            }
+            else
+            {
+              ReleaseKey(GetValEEPROM(j, i, LayerState[j][i]), GetTypeEEPROM(j, i, LayerState[j][i]));
+            }
           }
         }
 
@@ -352,7 +364,7 @@ void RotateLayers(byte val)
   /*
     Find the next layer within the bitfield.
     Limit iterations to 10, to ensure no infinite loop.
-   */
+  */
   for (int i = 0; i < 10; i++)
   {
     newLayer++;
@@ -395,6 +407,7 @@ void ResetPins()
     for (int j = 0; j < COL; j++)
     {
       KeyState[j][i] = 0;
+      KeyStateDebounced[j][i] = 0;
       PreviousState[j][i] = 0;
     }
   }
```

**Comment by joefiorini** [comment]
So since introducing the debouncing 8  days ago, I'm still noticing a high incident of key repeats and the occasional "stuck key". Repeats to happen most with "f" and "space", with some other keys thrown in sometimes, occurs whether or not I'm holding down modifiers with it (ie. using Meta+f in emacs sometimes goes fforward multiple spaces even though i pressed the keyonce), and will repeat up to 6 or 7 times. Sticking seems to happen most often when I have to hold down shift with another key, especially "-" (to get "_") and "'" to get """. I also have to try multiple times to get capitals to show up sometimes.

Another thing I've noticed about all this is that it seems to be the worst when I'm rapidly typing a lot of text like an email or a long Slack message. I spend about halff my time typing correcting repeated keystrokes.

I'm not sure where the problem is coming from, but i think i've ruled out debouncing as a solution. I _think_ it's helping a bit, but hasn't solved the entire problem. I'm not sure where to look next, but I think it'd be good to discern whether it's a hardware or software issue. Where would be the best place to determine that? i'd appreciate any tips on troubleshooting this so i can try to post more details here and get this problem solved.

**Comment by blahlicus** [comment]
Hey, your debouncing algorithm does not account for separate debounce times for each physical button, so it wouldn't work well with a device with a lot of keys (such as a keyboard where people press different keys with multiple fingers).

I am working on the experimental x2.6 build and I've implemented an advance debounce checker on [this commit](https://github.com/blahlicus/animus-family/commit/ac3da7ddf763f6555b19865406314b5b3a46c04a) which seems to be working very well so far.

Try out [this Animus build I've attached](https://github.com/blahlicus/animus-family/files/1355862/diverge-2.zip) below on your device, and see if it helps, `refreshDelay` is set to `1` by default so you'll probably still experience some debounce, if so, increment `refreshDelay` in `animus.ino` until you experience no debounce, some value between 4-8 should work but something lower should also work and give several ms more responsiveness (not that several ms really matters).

Also make sure to upload to your slave side as well, the x2.6 build needs to be uploaded to the slave side too.

**Comment by joefiorini** [comment]
Thanks @blahlicus! I've uploaded the latest code onto my Diiiverge. (either my Arduino IDE was acting weird or the attached build had the wrong code  in it; either way, I pulled the latest code and updated from that). II'm still noticing some repeats/stickiness, but time will tell if it's less. After a bit I'll try bumping my `refreshDelay` from 5 to 8.

**Comment by BurnzZ** [comment]
Hi @joefiorini

Any news on your fix? I also have this problem that happens 10% of the time. In addition, I also have these weird keypresses that are invoked even when I don't press them.

I'm observing this issue happens when typing very fast. Kind of puts a speed limit for your WPM :p 

Keyboard details: Diverge 3, Animus Innova 2.3.1

**Comment by blahlicus** [comment]
Completed as of [x3.0.0 release](https://github.com/blahlicus/animus-family/releases/tag/x3.0.0).

**Comment by blahlicus** [comment]
Also ported over to [2.7.0 release](https://github.com/blahlicus/animus-family/releases/tag/v2.7.0).
