### ISSUE TITLE
Expire tap dance reading immediately upon match

### ISSUE THREAD

**Issue by joefiorini** [blahlicus/animus-family#16]
I love the tap dance feature, but I'm finding it somewhat frustrating in its current implementation. I'm currently testing it out using it as such:

1. Press & hold for Fn
2. Tap twice for FnToggle

It does work, however I notice that I have to wait for the timeout to expire prior to being able to use my shifted layer keys. Ie. I have the W key on layer 1 mapped to the up arrow. If I press Fn+w it should always be "up" but if I press it too quickly then I get a "w" instead.

I'm wondering if it would make sense, when the first key in a tap dance combination is held down, to trigger the final press as soon as the I press a key to go with the modifier.

Thinking about this more, I'm not sure it makes total sense, but I can't think of another way to improve this behavior. I don't want to bring the delay setting too low, as it'd be frustrating to try to tap that quickly every time.

Maybe there's a better way to determine when to stop listening for the second tap dance key than using a delay?

**Comment by blahlicus** [comment]
> I'm wondering if it would make sense, when the first key in a tap dance combination is held down, to trigger the final press as soon as the I press a key to go with the modifier.

That is a good idea, we could make it so that the key in tapdance is sent if another key is pressed on the keyboard before the timeout expires, see behaviour below:

Assume tapdance timeout is set at 100ms and tapdance is set to `fn` for first tap, `togglefn` to second tap:

What currently happens is this:

* t=000ms -> tapdance key pressed
* t=010ms -> you press `w`, `w` is outputted
* t=100ms -> tapdance times out, fn is pressed, layer shifts to `layer1`

What we are proposing as a change:

* t=000ms -> tapdance key pressed
* t=010ms -> you press `w`, tapdance triggers, presses `fn`, layer shifts, then sends your `up` commandthrough
* t=100ms -> nothing happens, `fn` is already being held down.

**Comment by blahlicus** [comment]
The bad news is animus mods could not intercept and stop a key press from happening, it could detect key presses but not cancel them, I'll have to expand on the animus mod system to allow that. I'll get this update out alongside with Arbites 2.5, that should happen over the weekend.

**Comment by blahlicus** [comment]
Completed as of [x3.0.0 release](https://github.com/blahlicus/animus-family/releases/tag/x3.0.0).
