### ISSUE TITLE
Some key mappings do not send any input

### ISSUE THREAD

**Issue by slampisko** [blahlicus/animus-family#18]
Hello,

I noticed that when I try to map some keys to certain functions, nothing happens. I'm using [this utility](http://www.delphiforfun.org/Programs/Utilities/KeyCodes.htm) to detect key presses.

List of key mappings with no effect (that I noticed; there may be more):

- M Play
- M Pause
- KBSearch

Interesting about the M Play/M Pause mappings is that all other media mappings work -- they produce the expected output in the KeyCodes utility and I can control my media player and volume with them. I haven't tried other KB* mappings.

Also, i'd expect a 'M Stop' and 'M PlayPause' mapping instead of those two, that seems to be the standard. Can you clarify why it's 'M Play' and 'M Pause' instead?

Thank you!

**Comment by blahlicus** [comment]
Hey, that's because Animus performs media keys as a separate remote control, not as keyboard, Arduino's PluggableHID system allows multiple Human Interface Devices to connect to the host computer and the [AnimusMedia](https://github.com/blahlicus/animus-family/blob/master/mods/media/AnimusMedia.h) module has it's own separate HID.

As per the HID spec, there *is* a set of media keys, but basically no one uses it because it does not perform consistently across platforms (OS makers do not follow the standards properly), you could find the `KB [media]` keys at the `Others` tab of Arbites if you are interested in checking it out.

This is performing to spec to the firmware specifications so I'll just go ahead and close this, please feel free to reopen if you have any other questions related to this.
