### ISSUE TITLE
Diverge 3 animus master

### ISSUE THREAD

**Issue by metaquanta** [blahlicus/animus-family#22]
When I upload master/HEAD of this repo to my keyboard, most of the keys don't work and the others produce garbage.
If I upload the version in the zip found at https://unikeyboard.io/animus/ that is a bit older (animus-keyboard.h/cpp is still around) it works.
Is this a known problem?

**Comment by benji-york** [comment]
I think this may be helpful: https://www.reddit.com/r/Blahlicus/comments/6vt51z/animus_25_issues_with_diverge_tm_2/

**Comment by metaquanta** [comment]
Sure was. I suspected something like that. 
Is this documented somewhere?
The reddit thread mentions "release notes" but I can't seem to find any reference.
Also, are there plans to address this? 
Maintaining a fork of a library like this is almost never a good idea.

**Comment by blahlicus** [comment]
Release notes as in the github [release notes](https://github.com/blahlicus/animus-family/releases) for animus 2.5 mentioned the use of the separate HID library.

The Nicehood HID-Project library is no longer in active development and the only modification I did was editing a key mapping file in it so that it reads HID scancodes install of ASCII codes, so placing that library in this repo like this should be fine.

Animus is due for a refactor and upgrade at the moment to make it less coupled to Arduino and add support for expansion ICs (EEPROM and pin expanders), as part of that upgrade I will trim down the nicehood library to the parts that I need and release it as a separate repo properly.

I'll be closing this now since its not an error, feel free to reopen if you have any other questions.
